"""A setuptools based setup module.
See:
https://packaging.python.org/en/latest/distributing.html
https://github.com/pypa/sampleproject
Autogenerated by poetry-setup:
https://github.com/orsinium/poetry-setup
"""
# IMPORTANT: this file is autogenerated. Do not edit it manually.
# All changes will be lost after `poetry-setup` command execution.
# ----------------------------------------------------------------
# Always prefer setuptools over distutils
from setuptools import setup, find_packages
from os import path
# io.open is needed for projects that support Python 2.7
# It ensures open() defaults to text mode with universal newlines,
# and accepts an argument to specify the text encoding
# Python 3 only projects can skip this import
from io import open
here = path.abspath(path.dirname(__file__))
# Get the long description from the README file
with open(path.join(here, 'README.md'), encoding='utf-8') as f:
    long_description = f.read()
# Arguments marked as "Required" below must be included for upload to PyPI.
# Fields marked as "Optional" may be commented out.
setup(
    # https://packaging.python.org/specifications/core-metadata/#name
    name='mariner',  # Required
    # https://www.python.org/dev/peps/pep-0440/
    # https://packaging.python.org/en/latest/single_source_version.html
    version='1.3.0',  # Required
    # https://packaging.python.org/specifications/core-metadata/#summary
    description="Command line torrent searcher",  # Required
    # https://packaging.python.org/specifications/core-metadata/#description-optional
    long_description=long_description,  # Optional
    # https://packaging.python.org/specifications/core-metadata/#description-content-type-optional
    long_description_content_type='text/markdown',  # Optional (see note above)
    url="https://radek-sprta.gitlab.io/mariner/",  # Optional
    author="Radek Sprta",  # Optional
    author_email="mail@radeksprta.eu",  # Optional
    # For a list of valid classifiers, see https://pypi.org/classifiers/
    classifiers=[
        'Development Status :: 4 - Beta', 'Environment :: Console',
        'Intended Audience :: End Users/Desktop',
        'License :: OSI Approved :: GNU General Public License v3 (GPLv3)',
        'Natural Language :: English', 'Operating System :: POSIX :: Linux',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.5',
        'Programming Language :: Python :: 3.6',
        'Programming Language :: Python :: 3.7',
        'Topic :: Internet :: WWW/HTTP :: Indexing/Search'
    ],  # Optional
    keywords=' '.join(['cli', 'torrent', 'search', 'scraper',
                       'downloader']),  # Optional
    packages=find_packages(),  # Required
    # https://packaging.python.org/en/latest/requirements.html
    install_requires=[
        'aiodns (>=1.1.1,<2.0.0)',
        'aiofiles (>=0.4.0,<0.5.0)',
        'aiohttp (>=3.5.1,<4.0.0)',
        'bs4 (>=0.0.1,<0.0.2)',
        'cachalot (>=0.1.3)',
        'cliff (==2.9.1)',
        'cmd2 (==0.7.8)',
        'colorama (>=0.4.1,<0.5.0)',
        'future-fstrings (>=0.4.4,<0.5.0)',
        'lxml (>=4.2.5,<5.0.0)',
        'maya (>=0.6.0,<0.7.0)',
        'ruamel.yaml (>=0.15.82,<0.16.0)',
        'tokenize-rt (>=2.1.0,<3.0.0)',
    ],  # Optional
    # https://setuptools.readthedocs.io/en/latest/setuptools.html#dependencies-that-aren-t-in-pypi
    dependency_links=[],  # Optional
    # https://stackoverflow.com/a/16576850
    include_package_data=True,
    entry_points={  # Optional
        'console_scripts': [
            'mariner=mariner.main:main',
        ],
        'mariner.cli': [
            'config = mariner.commands.config:Config',
            'details = mariner.commands.details:Details',
            'download = mariner.commands.download:Download',
            'magnet = mariner.commands.magnet:Magnet',
            'open = mariner.commands.open:Open',
            'search = mariner.commands.search:Search',
        ],
    },
    # https://packaging.python.org/specifications/core-metadata/#project-url-multiple-use
    project_urls={  # Optional
        'homepage': 'https://radek-sprta.gitlab.io/mariner/',
    },
)
